version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      -MONGO-INITDB_ROOT_USERNAME: admin
      -MONGO-INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      -ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      -ME_CONFIG_MONGODB_ADMINPASSWORD: password
      -ME_CONFIG_MONGODB_SERVER: mongodb


