version: '3'
services:
#  nodejs_mongo_docker:
#    image: nodejs_mongo_docker_app
#    build:
#    environment:
#      NODE_ENV: production
#    ports:
#      - 3000:3000
#    volumes:
#      - .:user/src/app
#  postgres:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: password
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - data:/data/db
    environment:
      MONGO-INITDB_ROOT_USERNAME: admin
      MONGO-INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: products

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      -ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      -ME_CONFIG_MONGODB_ADMINPASSWORD: password
##      -ME_CONFIG_MONGODB_SERVER: mongodb
#      -ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/



