openapi: 3.0.3
info:
  title: ProductOrderingSystem
  description: ProductOrderingSystem
  version: 1.0.0
#servers:
#  - url: 'http://localhost:3000'
paths:
  /products:
    description: products endpoint
    get:
      description: operation to get the products
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
            example: 2
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productResponse'

        400:
          description: Invalid Request from user!
          content:
            application/json:
              schema:
                type: string
                example: error something happened
#        401:
#          description:
#        403:
#        404:


components:
  schemas:
    productResponse:
      type: object
      properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: bicycle
          description:
            type: string
            example: this is a bicycle with wheels
          price:
            type: number
            example: 35.30
          quantity:
            type: integer
            example: 34






